version: '3.7'
networks:
    minha-rede:
        driver: bridge

services:

    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - 8080:80
        networks:
            - minha-rede
        links:
            - php
        depends_on:
            - php

    php:
        build:
            context: .
        networks:
            - minha-rede
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: mysql:5.5
        command: --innodb-use-native-aio=0
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
            - ./sql/:/docker-entrypoint-initdb.d/
        environment:
            - MYSQL_DATABASE=meu-db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - minha-rede

volumes:
    mysql-data: