version: '3.7'
networks:
    minha-rede:
        driver: bridge

services:

    nginx:
        image: nginx:latest
        volumes:
            - ./www/:/usr/share/nginx/html/
            - ./conf/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        networks:
            - minha-rede
        links:
            - php
        depends_on:
            - php

    php:
        #image: php:7.3-fpm
        image: likesistemas/php:latest
        volumes:
            - ./www/:/var/www/html/
        networks:
            - minha-rede
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: mysql:5.5
        command: --innodb-use-native-aio=0
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
            - ./sql/:/docker-entrypoint-initdb.d/
        environment:
            - MYSQL_DATABASE=meu-db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - minha-rede

volumes:
    mysql-data: